

def CTL_CODE( DeviceType, Function, Method, Access ):
	return( (DeviceType << 16) | \
			(Access << 14) | \
			(Function << 2) | \
			Method )

FILE_DEVICE_UNKNOWN			= 0x00000022
METHOD_NEITHER				= 3
STANDARD_RIGHTS_REQUIRED	= 0x000F0000L
SYNCHRONIZE					= 0x00100000L
FILE_ALL_ACCESS				= (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF)



IOCTL_INIT_OREGANO					= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x801, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_DEBUG_PRINT					= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x802, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_ADD_TRACE_RANGE				= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x803, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_SET_PROCESS_INFO				= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x804, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_START_TRACE   				= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x805, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_STOP_TRACE      				= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x806, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_GET_LAST_BREAK_POINT_INFO		= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x807, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_PROBE_TRACE					= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x808, METHOD_NEITHER, FILE_ALL_ACCESS )
IOCTL_READ_BUFFER					= CTL_CODE( FILE_DEVICE_UNKNOWN, 0x809, METHOD_NEITHER, FILE_ALL_ACCESS )
